/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedTemasRouteImport } from './routes/_authenticated/temas'
import { Route as AuthenticatedSimuladosReaisRouteImport } from './routes/_authenticated/simulados-reais'
import { Route as AuthenticatedSimuladosRouteImport } from './routes/_authenticated/simulados'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedRedacaoRouteImport } from './routes/_authenticated/redacao'
import { Route as AuthenticatedQuestoesRouteImport } from './routes/_authenticated/questoes'
import { Route as AuthenticatedPlanoRouteImport } from './routes/_authenticated/plano'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMateriasRouteImport } from './routes/_authenticated/materias'
import { Route as AuthenticatedEstudosRouteImport } from './routes/_authenticated/estudos'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAulaTopicIdRouteImport } from './routes/_authenticated/aula.$topicId'
import { Route as AuthenticatedAulaTopicIdPraticaRouteImport } from './routes/_authenticated/aula.$topicId.pratica'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemasRoute = AuthenticatedTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladosReaisRoute =
  AuthenticatedSimuladosReaisRouteImport.update({
    id: '/simulados-reais',
    path: '/simulados-reais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimuladosRoute = AuthenticatedSimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedacaoRoute = AuthenticatedRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestoesRoute = AuthenticatedQuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoRoute = AuthenticatedPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriasRoute = AuthenticatedMateriasRouteImport.update({
  id: '/materias',
  path: '/materias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudosRoute = AuthenticatedEstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulaTopicIdRoute =
  AuthenticatedAulaTopicIdRouteImport.update({
    id: '/aula/$topicId',
    path: '/aula/$topicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAulaTopicIdPraticaRoute =
  AuthenticatedAulaTopicIdPraticaRouteImport.update({
    id: '/pratica',
    path: '/pratica',
    getParentRoute: () => AuthenticatedAulaTopicIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/materias': typeof AuthenticatedMateriasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/simulados-reais': typeof AuthenticatedSimuladosReaisRoute
  '/temas': typeof AuthenticatedTemasRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/aula/$topicId': typeof AuthenticatedAulaTopicIdRouteWithChildren
  '/aula/$topicId/pratica': typeof AuthenticatedAulaTopicIdPraticaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/estudos': typeof AuthenticatedEstudosRoute
  '/materias': typeof AuthenticatedMateriasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/plano': typeof AuthenticatedPlanoRoute
  '/questoes': typeof AuthenticatedQuestoesRoute
  '/redacao': typeof AuthenticatedRedacaoRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/simulados': typeof AuthenticatedSimuladosRoute
  '/simulados-reais': typeof AuthenticatedSimuladosReaisRoute
  '/temas': typeof AuthenticatedTemasRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/': typeof AuthenticatedIndexRoute
  '/aula/$topicId': typeof AuthenticatedAulaTopicIdRouteWithChildren
  '/aula/$topicId/pratica': typeof AuthenticatedAulaTopicIdPraticaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/estudos': typeof AuthenticatedEstudosRoute
  '/_authenticated/materias': typeof AuthenticatedMateriasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/plano': typeof AuthenticatedPlanoRoute
  '/_authenticated/questoes': typeof AuthenticatedQuestoesRoute
  '/_authenticated/redacao': typeof AuthenticatedRedacaoRoute
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/simulados': typeof AuthenticatedSimuladosRoute
  '/_authenticated/simulados-reais': typeof AuthenticatedSimuladosReaisRoute
  '/_authenticated/temas': typeof AuthenticatedTemasRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/aula/$topicId': typeof AuthenticatedAulaTopicIdRouteWithChildren
  '/_authenticated/aula/$topicId/pratica': typeof AuthenticatedAulaTopicIdPraticaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conquistas'
    | '/estudos'
    | '/materias'
    | '/perfil'
    | '/plano'
    | '/questoes'
    | '/redacao'
    | '/revisar'
    | '/simulados'
    | '/simulados-reais'
    | '/temas'
    | '/tutor'
    | '/aula/$topicId'
    | '/aula/$topicId/pratica'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/configuracoes'
    | '/conquistas'
    | '/estudos'
    | '/materias'
    | '/perfil'
    | '/plano'
    | '/questoes'
    | '/redacao'
    | '/revisar'
    | '/simulados'
    | '/simulados-reais'
    | '/temas'
    | '/tutor'
    | '/'
    | '/aula/$topicId'
    | '/aula/$topicId/pratica'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conquistas'
    | '/_authenticated/estudos'
    | '/_authenticated/materias'
    | '/_authenticated/perfil'
    | '/_authenticated/plano'
    | '/_authenticated/questoes'
    | '/_authenticated/redacao'
    | '/_authenticated/revisar'
    | '/_authenticated/simulados'
    | '/_authenticated/simulados-reais'
    | '/_authenticated/temas'
    | '/_authenticated/tutor'
    | '/_authenticated/'
    | '/_authenticated/aula/$topicId'
    | '/_authenticated/aula/$topicId/pratica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/temas': {
      id: '/_authenticated/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof AuthenticatedTemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulados-reais': {
      id: '/_authenticated/simulados-reais'
      path: '/simulados-reais'
      fullPath: '/simulados-reais'
      preLoaderRoute: typeof AuthenticatedSimuladosReaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulados': {
      id: '/_authenticated/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof AuthenticatedSimuladosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redacao': {
      id: '/_authenticated/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof AuthenticatedRedacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questoes': {
      id: '/_authenticated/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof AuthenticatedQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano': {
      id: '/_authenticated/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof AuthenticatedPlanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materias': {
      id: '/_authenticated/materias'
      path: '/materias'
      fullPath: '/materias'
      preLoaderRoute: typeof AuthenticatedMateriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudos': {
      id: '/_authenticated/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof AuthenticatedEstudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aula/$topicId': {
      id: '/_authenticated/aula/$topicId'
      path: '/aula/$topicId'
      fullPath: '/aula/$topicId'
      preLoaderRoute: typeof AuthenticatedAulaTopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aula/$topicId/pratica': {
      id: '/_authenticated/aula/$topicId/pratica'
      path: '/pratica'
      fullPath: '/aula/$topicId/pratica'
      preLoaderRoute: typeof AuthenticatedAulaTopicIdPraticaRouteImport
      parentRoute: typeof AuthenticatedAulaTopicIdRoute
    }
  }
}

interface AuthenticatedAulaTopicIdRouteChildren {
  AuthenticatedAulaTopicIdPraticaRoute: typeof AuthenticatedAulaTopicIdPraticaRoute
}

const AuthenticatedAulaTopicIdRouteChildren: AuthenticatedAulaTopicIdRouteChildren =
  {
    AuthenticatedAulaTopicIdPraticaRoute: AuthenticatedAulaTopicIdPraticaRoute,
  }

const AuthenticatedAulaTopicIdRouteWithChildren =
  AuthenticatedAulaTopicIdRoute._addFileChildren(
    AuthenticatedAulaTopicIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedEstudosRoute: typeof AuthenticatedEstudosRoute
  AuthenticatedMateriasRoute: typeof AuthenticatedMateriasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanoRoute: typeof AuthenticatedPlanoRoute
  AuthenticatedQuestoesRoute: typeof AuthenticatedQuestoesRoute
  AuthenticatedRedacaoRoute: typeof AuthenticatedRedacaoRoute
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedSimuladosRoute: typeof AuthenticatedSimuladosRoute
  AuthenticatedSimuladosReaisRoute: typeof AuthenticatedSimuladosReaisRoute
  AuthenticatedTemasRoute: typeof AuthenticatedTemasRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAulaTopicIdRoute: typeof AuthenticatedAulaTopicIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedEstudosRoute: AuthenticatedEstudosRoute,
  AuthenticatedMateriasRoute: AuthenticatedMateriasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanoRoute: AuthenticatedPlanoRoute,
  AuthenticatedQuestoesRoute: AuthenticatedQuestoesRoute,
  AuthenticatedRedacaoRoute: AuthenticatedRedacaoRoute,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedSimuladosRoute: AuthenticatedSimuladosRoute,
  AuthenticatedSimuladosReaisRoute: AuthenticatedSimuladosReaisRoute,
  AuthenticatedTemasRoute: AuthenticatedTemasRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAulaTopicIdRoute: AuthenticatedAulaTopicIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
